#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: adaptative-theme
#+date: \today
#+author: Álvaro Cortés Sánchez-Migallón
#+email: alvarocsm.91@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.0.50 (Org mode 9.3.6)
#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords: Emacs, Lisp, Scraping, Theme, Adaptative
#+subtitle: adaptative theme documentation
#+latex_compiler: pdflatex

\newpage

* adaptative-theme

  This file contain package function explanation, all use cases and description
  with examples. For more information contact me.

* Installation

  Easy to install, clone this project into your/.emacs.d/ folder and include
  next code at the end of your /init.el/ file.

  #+begin_src lisp
    (load-file "./adaptative-theme/adaptative-theme.el")
  #+end_src

* Requirements

  To use *adaptative-theme-location* scraping require /[[https://github.com/alphapapa/org-web-tools][org-web-tools]]/ package,
  installed when use the function thet require it. This package require /Emacs
  25.1/ or later varsion. This functions has been tested with my /init.el/
  configuration and /Emacs 28.0.50/.

  - Emacs 28.0.50
  - org-web-tools package (intalled when use)

* How to use

  You can use different functions included in /adaptative-theme.el/ file, in this
  section is explained how to use.

** adaptative-theme

   This is most simply function, only compare current hour with default or
   customized hour and load selected theme. This is faster function.

   Default time

   #+begin_src lisp
     (adaptative-theme 'gruvbox-light-soft 'gruvbox-dark-hard)
   #+end_src

   Customized time, am time 08:01:03, pm time 20:02:04.

   #+begin_src lisp
     (adaptative-theme 'gruvbox-light-soft 'gruvbox-dark-hard 08 20 01 02 03 04)
   #+end_src

** adaptative-theme-location

   This function allow to get am and pm time from the city that you want,
   thought to set your current city and country. Is slower than
   /adaptative-theme/ because require to access to internet to get data time.

   Please, search your city in https://www.timeanddate.com/sun to execute this
   function successfuly. As before function, have two methods, becouse have
   optional arguments.

   Default location. Madrid, Spain.

   #+begin_src lisp
     (adaptative-theme 'gruvbox-light-soft 'gruvbox-dark-hard)
   #+end_src

   Customized location, in munich city and germany as country.

   #+begin_src lisp
     (adaptative-theme-location 'gruvbox-light-soft
     'gruvbox-dark-hard "germany" "munich")
   #+end_src

** adaptarive-theme-autolocation

* Change log

** Ver/Rev: A/0

   First version include operative /adaptative-theme/ without errors and
   /adaptative-theme-location/ in debug stage.

* Development

  All contributions and suggersion are welcome, only thinking to improve.

** adaptative-theme

   At first we found different arguments, two needed, /light-theme/ that is
   loaded at day hours and /datk-theme/, that is loaded at night. The optional
   arguments are /am/ hour and /pm/ hour, you can choose both hours.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;; Adaptative theme function
     (defun adaptative-theme
       (light-theme dark-theme &optional am-hour pm-hour am-min pm-min am-sec pm-sec)
       " Adaptative theme function:
     @Brief:   This function allow to configure different themes depending on the
               emacs initialization time.

     @Author:  acsm

     @Version: A/0

     @Args:    light-theme: Theme loaded in sun hours.
               dark-theme:  Theme loaded in dark hours.
               &-am-hour: Custom dawn hour (0-23) (optional, default 07)
               &-pm-hour: Custom sunset hour (0-23) (optional, default 20)
               &-am-min:  Custom dawn min (0-59) (optional, default 00)
               &-pm-min:  Custom sunset min (0-59) (optional, default 00)
               &-am-sec:  Custom dawn sec (0-59) (optional, default 00)
               &-pm-sec:  Custom sunset sec (0-59) (optional, default 00)

     @Links:
     "
   #+end_src

   As it have optional values is important to define default values if this
   optional arguments are /nil/. I choose as default /7/ as dawn hour and /20/
   as sunset hour.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;;; Set default values
       ;; Set dawn time
       (unless (eval am-hour)
         (set 'am-hour 7))
       (unless (eval am-min)
         (set 'am-min 00))
       (unless (eval am-sec)
         (set 'am-sec 00))

       ;; Set sundown time
       (unless (eval pm-hour)
         (set 'pm-hour 20))
       (unless (eval pm-min)
         (set 'pm-min 00))
       (unless (eval pm-sec)
         (set 'pm-sec 00))
   #+end_src

   First of all, we need to get the initialization time to compare with the
   limits, we can get it with the descomposition of the current date in
   substrings, later we need to transform those substrings to integer to compare
   with inpus or default arguments.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;;; Get time
       (set 'init-time (current-time-string))

     ;;;; Get integer hour
       ;; Get hour
       (set 'init-hour-str (substring init-time 11 13))
       (set 'init-hour-int (string-to-number init-hour-str 10))
       ;; Get minute
       (set 'init-min-str (substring init-time 14 16))
       (set 'init-min-int (string-to-number init-min-str 10))
       ;; Get Second
       (set 'init-sec-str (substring init-time 17 19))
       (set 'init-sec-int (string-to-number init-sec-str 10))
   #+end_src

   Start thinking that is day, first, if current hour is lower than am hour,
   sure, is night, else if same hour compare minutes. As with hours if is the
   same hour and current minute is less than am minutes is night. Same with the seconds

   #+begin_src
             ,-----------------------------------------------,
             | Hour ,------------------------------,         |
   Night     |      | Minute      <-+->            |         |            Day
   ----------+------+---------------+--------------+---------+--------------
             |      |                Second        |         |
             |      '------------------------------'         |
             '-----------------------------------------------'
   #+end_src

   With the pm hour is the same but in the opposite.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;;; Detect if is day
       (set 'is-day t)
       (set 'is-morning nil)
       (set 'is-afternoon nil)

     ;;;;; Compare with am
     ;;;;;; Hour
       (if (< init-hour-int am-hour)
           ;; true if init hour <  dawn hour is night
           (set 'is-day nil)
         ;; Evaluate minutes if is the same hour
         (if (= init-hour-int am-hour)
             ;; evaluate minutes
             (if (< init-min-int am-min)
                 ;; true if init min <  dawn min is night
                 (set 'is-day nil)
               ;; Evaluate seconds if is the same minute
               (if (= init-sec-int am-sec)
                   ;; evaluate seconds
                   (if (< init-sec-int am-sec)
                       ;; true if init sec <  dawn sec is night
                       (set 'is-day nil)
                       )))
               )
           )

       ;; If isnt day is morning
       (if (null (eval is-day))
           (setq is-morning t))

     ;;;;; Compare with pm
     ;;;;;; Hour
       (if (> init-hour-int pm-hour)
           ;; true if init hour >  sunset hour is night
           (lambda ()
             (set 'is-day nil)
             (set 'is-afernoon t))
         ;; Evaluate minutes if is the same hour
         (if (= init-hour-int pm-hour)
             ;; evaluate minutes
             (if (> init-min-int pm-min)
                 ;; true if init min >  sunset min is night
                 (lambda ()
                   (set 'is-day nil)
                   (set 'is-afernoon t))
               ;; Evaluate seconds if is the same minute
               (if (= init-sec-int pm-sec)
                   ;; evaluate seconds
                   (if (> init-sec-int pm-sec)
                       ;; true if init sec >  sunset sec is night
                       (lambda ()
                         (set 'is-day nil)
                         (set 'is-afernoon t))))
               )
           )
         )

      ;; If isnt day now and is not morning is afternoon
      (if (null (eval is-day))
          (if (null (eval is-morning))
              (setq is-afternoon t)))
   #+end_src

   At the end load selected theme setting the timer to load future themes.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;;; Load theme
       (if is-day
           ;; Load ligth theme if is day
           (load-theme light-theme t)
         ;;(load-theme 'gruvbox-light-soft t)
         ;; Load dark theme if is not day
         (load-theme dark-theme t))
       ;;(load-theme 'gruvbox-dark-hard t))

     ;;;; Program nex theme change
       ;; Timer example
       ;;(run-at-time "5 sec" nil #'message "Prueba timer")
       ;;(run-at-time "20:30" nil #'kill-emacs)
       ;;(run-at-time "5 sec" nil #'adaptative-theme 'gruvbox-light-soft 'gruvbox-dark-hard)

       ;; If is day, reevaluate this function 10 seconds after sunset hour.
       (if (eval 'is-day)
           (lambda ()
             (setq prog-sec-time (+ (* 3600 (- pm-hour init-hour-int))
                                    (* 60 (- pm-min init-min-int))
                                    (- pm-sec init-sec-int)
                                    10))
             (setq prog-sec-time-str (concat (number-to-string prog-sec-time) " sec"))
             (run-at-time prog-sec-time-str nil #'adaptative-theme light-theme dark-theme)
             ))

       ;; If is morning, reevaluate this function at dawn hour
       (if (eval 'is-morning)
           (lambda ()
             (setq prog-sec-time (+ (* 3600 (- am-hour init-hour-int))
                                    (* 60 (- am-min init-min-int))
                                    (- am-sec init-sec-int)
                                    10))
             (setq prog-sec-time-str (concat (number-to-string prog-sec-time) " sec"))
             (run-at-time prog-sec-time-str nil #'adaptative-theme light-theme dark-theme)
             ))

       ;; If is afternoon, reevaluate this function at dawn hour. plus rest to midnight
       (if (eval 'is-afternoon)
           (lambda ()
             (setq prog-sec-time
                   (+ (* 3600 am-hour)
                      (* 60 am-min)
                      am-sec
                      10
                      (* 3600 (- 23 init-hour-int))
                      (* 60 (- 59 init-min-int))
                      (- 59 init-sec-int)))
             (setq prog-sec-time-str (concat (number-to-string prog-sec-time) " sec"))
             (run-at-time prog-sec-time-str nil #'adaptative-theme light-theme dark-theme)
             ))
     )
   #+end_src


** adaptative-theme-location

   This function have two arguments, light-theme and dark-themen, as optional
   arguments it have two, country and city to setect in which city you are and
   in function of this search am hour and pm hour to detect dawn and sunset
   time.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;; Adaptative theme location
     (defun adaptative-theme-location (ligth-theme dark-theme &optional country city)
       "  Adaptative theme location function:
     @Brief:   This function allow to configure different themes depending on your
               location when work emacs.

     @Author:  acsm

     @Version: A/0

     @Args:    light-theme: Theme loaded in sun hours.
               dark-theme:  Theme loaded in dark hours.
               &country:    Custom Country location (str) (optional, default spain)
               &city:       Custom City or capital location (str) (optional, default madrid)

     @Links:   https://www.timeanddate.com/sun where look for your country and city names.
     "
   #+end_src

    IF dont fill this arguments, you are going to have the *Madrid*, *Spain*
    hour. To make the scrapping this function require /org-web-tools/, this
    package is installed when use it.

    The web site where take the hours information is
    https://www.timeanddate.com/sun, is recomended to search your city in the
    web to avoid errors.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;;; Load basic requieres
     (require 'org-web-tools)

     ;;;; Web scraping
     ;; URL base to get am and pm data
     (setq url "https://www.timeanddate.com/sun")
     ;; Set default county
     (unless (eval country)
       (setq country "spain"))

     ;; Set default city
     (unless (eval city)
       (setq city "madrid"))
   #+end_src

   First is create the url to search the information, after that, is importart
   to download the web first to create the regular expression, i recomend to get
   the html and later create the regex in a web page, at the last, make it with
   emacs special syntaxis.

   Later get in which point os the html stris is the match, and get a subtring
   filtering all the web.

   #+begin_src lisp :tangle adaptative-theme.el
     ;; Compose url
     (setq web_to_scrap (concat url "/" country "/" city))
     (setq webDataHtml (org-web-tools--get-url web_to_scrap))
     ;; web string to search
     ;; <div class=\"h1 dn-mob\">Daylight</div><p class=dn-mob>7:18 &#8211; 21:06<br>13 hours, 48 minutes</p></div>
     ;; first regex model
     ;;>Daylight<\/div><p class=dn-mob>[0-9]{1,2}:[0-9]{1,2} &#8211; [0-9]{1,2}:[0-9]{1,2}<br>[0-9]{1,2} hours, [0-9]{1,2} minutes<\/p><\/div>
     ;; second regex model
     ;;\WDaylight\W{1,}div\W{1,}p\sclass\Wdn\Wmob\W[0-9]{1,2}\W[0-9]{1,2} \W{1,}[0-9]{1,}\W [0-9]{1,2}\W[0-9]{1,2}\Wbr\W[0-9]{1,2}\shours\W\s[0-9]{1,2}\sminutes\W{1,}p\W{1,}div\W
     ;; Helm regex model
     ;;\\s_Daylight\\s_\\{2\\}div\\s_\\{2\\}p\\s-class\\s_dn\\s_mob\\s_[0-9]\\{1,2\\}:[0-9]\\{1,2\\}\\s-\\s_\\{1,\\}
     ;;;; Web regex model
     (setq webRegexModel "\\s_Daylight\\s_\\{2\\}div\\s_\\{2\\}p\\s-class\\s_dn\\s_mob\\s_[0-9]\\{1,2\\}:[0-9]\\{1,2\\}\\s-\\s_\\{1,\\}")

     ;;;; Extract regex value
     (setq daylight-regex
           (string-match webRegexModel webDataHtml))

     ;;;; Extract substring
     (setq subWebStr
           (substring webDataHtml daylight-regex (+ daylight-regex 100)))
   #+end_src

   Later regenerate the regex to extract am hour and pm hour from the html
   substring.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;;; Create regex group time
     (setq timeGroupRegex "[0-9]\\{1,2\\}:[0-9]\\{1,2\\}")

     ;;;; Extract time value as string
     (setq timeStr (string-match timeGroupRegex subWebStr))

     ;;;; Extract AM hour
     (setq amTime (substring subWebStr timeStr (+ timeStr 5)))

     ;;;; Get substring pm time
     (setq timeStr (string-match timeGroupRegex subWebStr (+ timeStr 6)))

     ;;;; Extract PM time
     (setq pmTime (substring subWebStr timeStr (+ timeStr 5)))

     ;;;; Regenerate time regext to get hour and minutes
     (setq timeGroupRegex ":")

     ;;;; Get AM Hour
     (setq amSeparator (string-match timeGroupRegex amTime))
     (setq amHourStr (substring amTime 0 amSeparator))
     (setq amHourInt (string-to-number amHourStr))

     ;;;; Get AM Min
     (setq amSeparator (string-match timeGroupRegex amTime))
     (setq amMinStr (substring amTime (+ amSeparator 1) (+ amSeparator 3)))
     (setq amMinInt (string-to-number amMinStr))

     ;;;; Get PM Hour
     (setq pmSeparator (string-match timeGroupRegex pmTime))
     (setq pmHourStr (substring pmTime 0 pmSeparator))
     (setq pmHourInt (string-to-number pmHourStr))

     ;;;; Get PM Min
     (setq pmSeparator (string-match timeGroupRegex pmTime))
     (setq pmMinStr (substring pmTime (+ pmSeparator 1) (+ pmSeparator 3)))
     (setq pmMinInt (string-to-number pmMinStr))
   #+end_src

   Execute adaptative theme function with the hour got from web.

   #+begin_src lisp :tangle adaptative-theme.el
     ;;;; Execute adaptative theme function
     (adaptative-theme ligth-theme dark-theme amHourInt pmHourInt amMinInt pmMinInt))
   #+end_src

** adaptarive-theme-autolocation

   https://mylocation.org/

* Liscence

  GPLv3
